
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Brownell Chalstrom
email: brownell@chalstrom.com
description: >- # this means to ignore newlines until "baseurl:"
  Information about consulting, sailing, and other things
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://brownell.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: bchalstrom
github_username:  brownell

theme: jekyll-theme-leap-day